# learning params
learning_rate: 0.00001
gamma: 0.95
buffer_limit: 500000
batch_size: 128
sim_len: 4500
mem_refill: 1000
epochs: 1600
n_cars: 1000
weights_path: ''

# SUMO params
sumoBinary: "/usr/local/opt/sumo/share/sumo/bin/sumo-gui"
sumoCmd: "/Users/suess_mann/wd/tcqdrl/intelligent_traffic_lights/src/cfg/sumo_config.sumocfg"
sumoTools: "/usr/local/opt/sumo/share/sumo/tools"